export interface FallbackQuestion {
  id: number;
  text: string;
  options: string[];
  correctAnswer: number;
  level: 100 | 200 | 300 | 400;
  topic: string;
}

export const fallbackQuestions: FallbackQuestion[] = [
  // 100 LEVEL: INTRODUCTION TO FINANCE
  { id: 1, text: "Which financial statement reports a company's financial position at a point in time?", options: ["Income Statement", "Balance Sheet", "Cash Flow Statement", "Retained Earnings"], correctAnswer: 1, level: 100, topic: "General" },
  { id: 2, text: "The concept that 'a Naira today is worth more than a Naira tomorrow' is known as:", options: ["Inflation", "Time Value of Money", "Opportunity Cost", "Liquidity Preference"], correctAnswer: 1, level: 100, topic: "General" },
  { id: 3, text: "Which of the following is a primary market transaction?", options: ["Buying stock on the NSE", "An Initial Public Offering (IPO)", "Selling shares to a friend", "A corporate share buy-back"], correctAnswer: 1, level: 100, topic: "Financial Markets" },
  { id: 4, text: "What is the primary objective of a firm in financial management?", options: ["Profit Maximization", "Cost Minimization", "Shareholder Wealth Maximization", "Tax Evasion"], correctAnswer: 2, level: 100, topic: "General" },
  { id: 5, text: "The ratio of Current Assets to Current Liabilities is known as:", options: ["Quick Ratio", "Current Ratio", "Debt Ratio", "Profitability Ratio"], correctAnswer: 1, level: 100, topic: "Ratio Analysis" },
  { id: 6, text: "Which entity regulates the Nigerian capital market?", options: ["Central Bank of Nigeria (CBN)", "Security and Exchange Commission (SEC)", "Federal Ministry of Finance", "Standard Organization of Nigeria"], correctAnswer: 1, level: 100, topic: "Financial Markets" },
  { id: 7, text: "Compound interest is calculated on:", options: ["Principal only", "Accrued interest only", "Principal and accumulated interest", "Government bonds"], correctAnswer: 2, level: 100, topic: "General" },
  { id: 8, text: "Which of these is considered a 'Paper Asset'?", options: ["Real Estate", "Gold", "Stocks", "Machinery"], correctAnswer: 2, level: 100, topic: "General" },
  { id: 9, text: "A market where long-term debt and equity are traded is the:", options: ["Money Market", "Capital Market", "Commodity Market", "Foreign Exchange Market"], correctAnswer: 1, level: 100, topic: "Financial Markets" },
  { id: 10, text: "What does 'ROI' stand for?", options: ["Rate Of Interest", "Return On Investment", "Revenue Of Industry", "Ratio Of Income"], correctAnswer: 1, level: 100, topic: "General" },
  { id: 41, text: "Which of the following is not a source of long-term finance?", options: ["Preference shares", "Debentures", "Trade credit", "Equity shares"], correctAnswer: 2, level: 100, topic: "Finance Sources" },
  { id: 42, text: "The money market is a market for:", options: ["Short-term funds", "Long-term funds", "Medium-term funds", "All of the above"], correctAnswer: 0, level: 100, topic: "Money Market" },
  { id: 43, text: "The term 'Bull' in stock market refers to:", options: ["An investor who expects price rise", "An investor who expects price fall", "A cautious investor", "An aggressive trader"], correctAnswer: 0, level: 100, topic: "Stock Exchange" },
  { id: 101, text: "Which of the following is a money market instrument?", options: ["Equity Shares", "Debentures", "Treasury Bills", "Long-term Bonds"], correctAnswer: 2, level: 100, topic: "Financial Instruments" },
  { id: 102, text: "Bank rate is the rate at which:", options: ["Central Bank lends to commercial banks", "Banks lend to public", "Banks lend to each other", "Government borrows"], correctAnswer: 0, level: 100, topic: "Banking" },
  { id: 103, text: "A crossed cheque can be encashed:", options: ["At the counter", "Only through a bank account", "By anyone", "At any bank branch"], correctAnswer: 1, level: 100, topic: "Banking" },
  { id: 104, text: "Which of the following represents the accounting equation?", options: ["Assets = Liabilities - Equity", "Assets = Liabilities + Equity", "Equity = Assets + Liabilities", "Liabilities = Equity - Assets"], correctAnswer: 1, level: 100, topic: "Accounting" },
  { id: 105, text: "An asset that can be converted into cash within one year is known as a:", options: ["Fixed Asset", "Current Asset", "Intangible Asset", "Fictitious Asset"], correctAnswer: 1, level: 100, topic: "Accounting" },
  { id: 106, text: "What is the main purpose of the Cash Flow Statement?", options: ["To show profitability", "To show financial position", "To show sources and uses of cash", "To show owner's equity"], correctAnswer: 2, level: 100, topic: "Financial Statements" },
  { id: 107, text: "A liability that is due to be paid in more than one year is a:", options: ["Current Liability", "Contingent Liability", "Long-term Liability", "Unfunded Liability"], correctAnswer: 2, level: 100, topic: "Accounting" },

  // 200 LEVEL: CORPORATE FINANCE & ACCOUNTING
  { id: 11, text: "Net Present Value (NPV) is positive when:", options: ["IRR > Cost of Capital", "IRR < Cost of Capital", "Cost of Capital = 0", "Cash inflows are zero"], correctAnswer: 0, level: 200, topic: "Capital Budgeting" },
  { id: 12, text: "Which capital budgeting technique does NOT consider the Time Value of Money?", options: ["Internal Rate of Return", "Payback Period", "Profitability Index", "Net Present Value"], correctAnswer: 1, level: 200, topic: "Capital Budgeting" },
  { id: 13, text: "Working capital management involves managing:", options: ["Long term assets", "Shareholder equity", "Short term assets and liabilities", "Tax liabilities"], correctAnswer: 2, level: 200, topic: "Working Capital" },
  { id: 14, text: "Operating leverage measures the sensitivity of a company's EBIT to changes in its:", options: ["Interest rates", "Sales", "Tax rates", "Stock price"], correctAnswer: 1, level: 200, topic: "Leverage" },
  { id: 15, text: "What is 'WACC' in corporate finance?", options: ["Weighted Average Cost of Capital", "Weekly Average Cash Collection", "Western African Currency Code", "Weighted Asset Credit Cost"], correctAnswer: 0, level: 200, topic: "Cost of Capital" },
  { id: 16, text: "The mix of a firm's permanent long-term financing is called:", options: ["Financial structure", "Capital structure", "Asset structure", "Owner structure"], correctAnswer: 1, level: 200, topic: "Capital Structure" },
  { id: 17, text: "Modigliani-Miller Theorem, with taxes, suggests that firm value increases with:", options: ["Equity", "Debt", "Cash", "Retained Earnings"], correctAnswer: 1, level: 200, topic: "Capital Structure" },
  { id: 18, text: "The point where a project's NPV is zero is the:", options: ["Break-even point", "Optimal point", "Internal Rate of Return (IRR)", "Profitability threshold"], correctAnswer: 2, level: 200, topic: "Capital Budgeting" },
  { id: 19, text: "Inventory turnover is a measure of:", options: ["Liquidity", "Efficiency", "Profitability", "Leverage"], correctAnswer: 1, level: 200, topic: "Ratio Analysis" },
  { id: 20, text: "Agency problem arises due to conflict of interest between:", options: ["Bankers and customers", "Managers and Shareholders", "Government and Firms", "Suppliers and Buyers"], correctAnswer: 1, level: 200, topic: "Corporate Governance" },
  { id: 51, text: "Which of the following is a component of working capital?", options: ["Machinery", "Building", "Cash and Bank balances", "Long-term loans"], correctAnswer: 2, level: 200, topic: "Working Capital" },
  { id: 52, text: "Dividend payout ratio is the:", options: ["Dividend as % of market price", "Dividend as % of earnings", "Dividend as % of face value", "Dividend as % of book value"], correctAnswer: 1, level: 200, topic: "Dividend Policy" },
  { id: 201, text: "In capital budgeting, 'hurdle rate' is often the:", options: ["Internal rate of return", "Cost of capital", "Risk-free rate", "Accounting rate of return"], correctAnswer: 1, level: 200, topic: "Capital Budgeting" },
  { id: 202, text: "The dividend growth model (Gordon Growth Model) is used for:", options: ["Valuing stocks", "Valuing bonds", "Calculating WACC", "Project selection"], correctAnswer: 0, level: 200, topic: "Dividend Model" },
  { id: 203, text: "Operating cycle refers to the time needed to:", options: ["Pay liabilities", "Convert cash into inventory and back to cash", "Produce a product", "Sell inventory"], correctAnswer: 1, level: 200, topic: "Working Capital" },
  { id: 204, text: "A stock split typically results in:", options: ["A higher stock price", "A lower stock price", "No change in total market value", "An increase in total market value"], correctAnswer: 2, level: 200, topic: "Equities" },
  { id: 205, text: "Financial leverage is the use of:", options: ["Fixed assets to magnify returns", "Borrowed capital to finance assets", "Equity to reduce risk", "Retained earnings for growth"], correctAnswer: 1, level: 200, topic: "Leverage" },
  { id: 206, text: "Which component of WACC must be adjusted for taxes?", options: ["Cost of Equity", "Cost of Preferred Stock", "Cost of Debt", "All of the above"], correctAnswer: 2, level: 200, topic: "Cost of Capital" },
  { id: 207, text: "The 'pecking order theory' of capital structure suggests firms prefer financing from:", options: ["New equity, then debt, then internal funds", "Debt, then new equity, then internal funds", "Internal funds, then debt, then new equity", "New equity, then internal funds, then debt"], correctAnswer: 2, level: 200, topic: "Capital Structure" },

  // 300 LEVEL: INVESTMENTS & FINANCIAL ANALYSIS
  { id: 21, text: "Systematic risk is also known as:", options: ["Diversifiable risk", "Market risk", "Unique risk", "Asset-specific risk"], correctAnswer: 1, level: 300, topic: "Risk & Return" },
  { id: 22, text: "A stock's beta measures its:", options: ["Total risk", "Sensitivity to market movements", "Dividend yield", "Earnings growth"], correctAnswer: 1, level: 300, topic: "Risk & Return" },
  { id: 23, text: "According to CAPM, the expected return on a security is composed of the risk-free rate and a:", options: ["Liquidity premium", "Maturity premium", "Risk premium", "Default premium"], correctAnswer: 2, level: 300, topic: "Investments" },
  { id: 24, text: "The 'Efficient Frontier' represents portfolios that offer the:", options: ["Highest possible risk", "Lowest possible return", "Highest expected return for a given level of risk", "Guaranteed return"], correctAnswer: 2, level: 300, topic: "Portfolio Theory" },
  { id: 25, text: "A bond sold at a price higher than its face value is trading at a:", options: ["Discount", "Premium", "Par", "Yield"], correctAnswer: 1, level: 300, topic: "Bonds" },
  { id: 26, text: "The relationship between bond prices and interest rates is typically:", options: ["Direct", "Stable", "Inverse", "Irrelevant"], correctAnswer: 2, level: 300, topic: "Bonds" },
  { id: 27, text: "Technical analysis primarily involves studying:", options: ["Company financial statements", "Market prices and volume data", "Management quality", "Macroeconomic forecasts"], correctAnswer: 1, level: 300, topic: "Investments" },
  { id: 28, text: "A portfolio with a beta of 1.0 is expected to:", options: ["Outperform the market", "Move in line with the market", "Be risk-free", "Have zero return"], correctAnswer: 1, level: 300, topic: "Investments" },
  { id: 29, text: "The primary tool for reducing unsystematic risk in a portfolio is:", options: ["Leverage", "Diversification", "Short Selling", "Margin Trading"], correctAnswer: 1, level: 300, topic: "Portfolio Theory" },
  { id: 30, text: "Intrinsic value is most associated with:", options: ["Fundamental Analysis", "Technical Analysis", "Efficient Market Hypothesis", "Speculation"], correctAnswer: 0, level: 300, topic: "Investments" },
  { id: 61, text: "Which of the following is not a derivative instrument?", options: ["Options", "Futures", "Common Stock", "Swaps"], correctAnswer: 2, level: 300, topic: "Derivatives" },
  { id: 62, text: "The price-earnings (P/E) ratio is a measure of:", options: ["Company liquidity", "Market price relative to earnings per share", "Operating efficiency", "Capital structure"], correctAnswer: 1, level: 300, topic: "Security Analysis" },
  { id: 301, text: "A portfolio having many different assets from various sectors is called a:", options: ["Concentrated portfolio", "Diversified portfolio", "Risky portfolio", "Optimal portfolio"], correctAnswer: 1, level: 300, topic: "Portfolio Theory" },
  { id: 302, text: "The Sharpe ratio measures:", options: ["Total risk per unit of return", "Risk-adjusted return", "Market risk per unit of return", "Standard deviation"], correctAnswer: 1, level: 300, topic: "Performance Measurement" },
  { id: 303, text: "Interest rate parity theory relates:", options: ["Inflation and exchange rates", "Interest rates and exchange rates", "GDP and exchange rates", "Trade balance and exchange rates"], correctAnswer: 1, level: 300, topic: "International Finance" },
  { id: 304, text: "A 'blue-chip' stock typically refers to a company that is:", options: ["New and fast-growing", "Financially stable and well-established", "In the technology sector", "Highly volatile"], correctAnswer: 1, level: 300, topic: "Equities" },
  { id: 305, text: "The semi-strong form of the Efficient Market Hypothesis states that prices reflect:", options: ["Past prices only", "All public information", "All public and private information", "Only insider information"], correctAnswer: 1, level: 300, topic: "Market Theory" },
  { id: 306, text: "A bond's yield to maturity (YTM) is the:", options: ["Annual coupon payment", "Total return anticipated if the bond is held until it matures", "Current market price", "Face value of the bond"], correctAnswer: 1, level: 300, topic: "Bonds" },

  // 400 LEVEL: ADVANCED FINANCE & DERIVATIVES
  { id: 31, text: "A contract giving the right but not the obligation to buy an asset at a specified price is a:", options: ["Forward contract", "Futures contract", "Call Option", "Put Option"], correctAnswer: 2, level: 400, topic: "Derivatives" },
  { id: 32, text: "The Black-Scholes model is used primarily for pricing:", options: ["Bonds", "Stocks", "European-style Options", "Real Estate"], correctAnswer: 2, level: 400, topic: "Derivatives" },
  { id: 33, text: "In a merger, if the acquirer pays more than the fair market value of the target's net assets, the excess is recorded as:", options: ["Operating profit", "Goodwill", "Capital gain", "Synergy"], correctAnswer: 1, level: 400, topic: "M&A" },
  { id: 34, text: "A 'LBO' stands for:", options: ["Liquid Business Option", "Leveraged Buyout", "Large Bank Overdraft", "Long-term Bond Obligation"], correctAnswer: 1, level: 400, topic: "Corporate Finance" },
  { id: 35, text: "The risk that a company's financial statements will be affected by exchange rate fluctuations is:", options: ["Transaction Risk", "Translation Risk", "Economic Risk", "Currency Risk"], correctAnswer: 1, level: 400, topic: "International Finance" },
  { id: 36, text: "In portfolio management, 'alpha' represents:", options: ["Systematic risk", "Total risk", "Return in excess of the expected market return", "The risk-free rate"], correctAnswer: 2, level: 400, topic: "Advanced Theory" },
  { id: 37, text: "Arbitrage involves profiting from:", options: ["Long-term economic growth", "Price discrepancies in different markets", "High interest rates", "Government subsidies"], correctAnswer: 1, level: 400, topic: "Investments" },
  { id: 38, text: "A currency swap involves exchanging:", options: ["Interest rates only", "Principal and/or interest payments in different currencies", "Equity for debt", "Physical cash"], correctAnswer: 1, level: 400, topic: "International Finance" },
  { id: 39, text: "Which derivative is typically traded on an exchange with daily marking-to-market?", options: ["Forward contract", "Futures contract", "Swap", "Over-the-counter Option"], correctAnswer: 1, level: 400, topic: "Derivatives" },
  { id: 40, text: "Capital Flight refers to:", options: ["Government spending abroad", "Large-scale exit of financial assets from a country", "Aviation industry investment", "A stock market crash"], correctAnswer: 1, level: 400, topic: "Macro-Finance" },
  { id: 71, text: "A horizontal merger occurs between firms that are:", options: ["In different industries", "Competitors in the same industry", "At different stages of production", "In related but distinct industries"], correctAnswer: 1, level: 400, topic: "Mergers" },
  { id: 72, text: "The risk that a counterparty will not fulfill its contractual obligation is:", options: ["Market risk", "Credit risk", "Liquidity risk", "Operational risk"], correctAnswer: 1, level: 400, topic: "Risk Management" },
  { id: 401, text: "A 'Straddle' option strategy involves buying a call and a put on the same asset with the same:", options: ["Strike price only", "Expiration date only", "Strike price and expiration date", "Premium"], correctAnswer: 2, level: 400, topic: "Option Strategies" },
  { id: 402, text: "Securitization is the process of:", options: ["Issuing new company shares", "Pooling assets and selling interests in the pool as securities", "Buying back corporate debt", "Hedging against market risk"], correctAnswer: 1, level: 400, topic: "Financial Innovation" },
  { id: 403, text: "A 'poison pill' is a defense tactic used by a company to:", options: ["Increase its stock price", "Prevent or discourage a hostile takeover", "Pay off its debts", "Attract new investors"], correctAnswer: 1, level: 400, topic: "M&A" },
  { id: 404, text: "Value at Risk (VaR) is a statistical measure of:", options: ["The maximum potential loss on a portfolio over a given time period", "The average return of a portfolio", "The beta of a portfolio", "The total assets of a company"], correctAnswer: 0, level: 400, topic: "Risk Management" },
  { id: 405, text: "What does 'FinTech' primarily refer to?", options: ["A new financial theory", "Technology used to improve and automate financial services", "A type of cryptocurrency", "A government financial regulation"], correctAnswer: 1, level: 400, topic: "Modern Finance" },
  { id: 406, text: "A 'Junk Bond' is a bond that is:", options: ["Rated investment grade", "Issued by the government", "Rated below investment grade", "Zero-coupon"], correctAnswer: 2, level: 400, topic: "Bonds" },
  { id: 407, text: "In behavioral finance, 'herding' refers to the tendency for investors to:", options: ["Follow their own research", "Follow the actions of a larger group", "Invest in agricultural stocks", "Diversify their portfolio"], correctAnswer: 1, level: 400, topic: "Behavioral Finance" },
];