
import { jsPDF } from "jspdf";

export const generatePDF = (title: string, content: string, courseCode: string, year: number) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;

  // Header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("ADEKUNLE AJASIN UNIVERSITY, AKUNGBA-AKOKO", pageWidth / 2, 20, { align: "center" });
  
  doc.setFontSize(14);
  doc.text("FINANCE STUDENTS' ASSOCIATION", pageWidth / 2, 28, { align: "center" });

  doc.setLineWidth(0.5);
  doc.line(margin, 35, pageWidth - margin, 35);

  // Course Info
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Course Code: ${courseCode}`, margin, 45);
  doc.text(`Year: ${year}`, pageWidth - margin - 30, 45); // Approximate right align
  
  doc.setFont("helvetica", "bold");
  doc.text(`Course Title: ${title}`, margin, 52);

  doc.line(margin, 58, pageWidth - margin, 58);

  // Content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const splitText = doc.splitTextToSize(content, maxLineWidth);
  doc.text(splitText, margin, 68);

  // Footer
  // Use 'any' cast to bypass strict type checking on internal properties if types are mismatched
  const pageCount = (doc as any).internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.text(`Page ${i}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
      doc.text("Generated by FINSA Portal", margin, doc.internal.pageSize.getHeight() - 10);
  }

  return doc;
};

export const downloadPDF = (title: string, content: string, courseCode: string, year: number) => {
    const doc = generatePDF(title, content, courseCode, year);
    doc.save(`${courseCode}_${year}_PastQuestion.pdf`);
};

export const generateTestReviewPDF = (questions: any[], userAnswers: Record<number, number>, score: number, user: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let yPos = 20;

    // Header
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("TEST RESULT SUMMARY", pageWidth / 2, yPos, { align: "center" });
    yPos += 10;
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Student: ${user?.name || 'Guest'}`, margin, yPos);
    yPos += 7;
    doc.text(`Score: ${score}%`, margin, yPos);
    yPos += 7;
    doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPos);
    yPos += 15;

    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;

    // Questions
    doc.setFontSize(11);
    
    questions.forEach((q, idx) => {
        // Check page break
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }

        doc.setFont("helvetica", "bold");
        const qTitle = `Q${idx + 1}: ${q.text}`;
        const splitTitle = doc.splitTextToSize(qTitle, maxLineWidth);
        doc.text(splitTitle, margin, yPos);
        yPos += (splitTitle.length * 7);

        doc.setFont("helvetica", "normal");
        q.options.forEach((opt: string, optIdx: number) => {
            const isCorrect = q.correctAnswer === optIdx;
            const isSelected = userAnswers[idx] === optIdx;
            
            let prefix = "   ";
            if (isCorrect) prefix = " (Correct) ";
            if (isSelected) prefix = " (Your Answer) ";
            if (isCorrect && isSelected) prefix = " (Correct & Your Answer) ";

            const optText = `${String.fromCharCode(65+optIdx)}. ${opt} ${prefix}`;
            const splitOpt = doc.splitTextToSize(optText, maxLineWidth);
            
            if (isCorrect) doc.setTextColor(0, 150, 0); // Green
            else if (isSelected && !isCorrect) doc.setTextColor(200, 0, 0); // Red
            else doc.setTextColor(100, 100, 100); // Grey

            doc.text(splitOpt, margin + 5, yPos);
            doc.setTextColor(0, 0, 0); // Reset
            yPos += (splitOpt.length * 6);
        });
        
        yPos += 8; // Spacing between questions
    });

    doc.save(`FINQUEST_Test_Result_${new Date().toISOString().split('T')[0]}.pdf`);
};
