import { jsPDF } from "jspdf";

const renderMarkdownContent = (doc: jsPDF, markdown: string, startX: number, startY: number, maxWidth: number) => {
    let y = startY;
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const lineHeight = 7;

    const checkPageBreak = (neededHeight: number) => {
        if (y + neededHeight > pageHeight - margin) {
            doc.addPage();
            y = margin;
        }
    };

    const renderStyledLine = (line: string) => {
        const regex = /(\*\*.*?\*\*|_.*?_|~~.*?~~)/g;
        const parts = line.split(regex).filter(part => part);

        let currentX = startX;
        checkPageBreak(lineHeight);

        for (const part of parts) {
            let isBold = false;
            let isItalic = false;
            let isStrike = false;
            let text = part;

            if (part.startsWith('**') && part.endsWith('**')) {
                isBold = true;
                text = part.substring(2, part.length - 2);
            } else if (part.startsWith('_') && part.endsWith('_')) {
                isItalic = true;
                text = part.substring(1, part.length - 1);
            } else if (part.startsWith('~~') && part.endsWith('~~')) {
                isStrike = true;
                text = part.substring(2, part.length - 2);
            }
            
            let fontStyle = 'normal';
            if (isBold && isItalic) fontStyle = 'bolditalic';
            else if (isBold) fontStyle = 'bold';
            else if (isItalic) fontStyle = 'italic';
            doc.setFont('helvetica', fontStyle);

            const words = text.split(' ');
            for (let i = 0; i < words.length; i++) {
                const word = words[i] + (i === words.length - 1 ? '' : ' ');
                const wordWidth = doc.getStringUnitWidth(word) * doc.getFontSize() / doc.internal.scaleFactor;

                if (currentX + wordWidth > startX + maxWidth) {
                    currentX = startX;
                    y += lineHeight;
                    checkPageBreak(lineHeight);
                }
                
                doc.text(word, currentX, y, { flags: { 'strikeout': isStrike } });
                currentX += wordWidth;
            }
        }
        y += lineHeight; // Move to the next line after the full line is processed
    };

    const lines = markdown.split('\n');

    for (const line of lines) {
        if (line.startsWith('## ')) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(14);
            const text = line.substring(3);
            const splitText = doc.splitTextToSize(text, maxWidth);
            checkPageBreak(splitText.length * 8 + 4);
            doc.text(splitText, startX, y);
            y += splitText.length * 8 + 4;
        } else if (line.startsWith('* ') || line.startsWith('- ')) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
            const text = line.substring(2);
            const splitText = doc.splitTextToSize(text, maxWidth - 5);
            checkPageBreak(splitText.length * 5 + 2);
            doc.text(`•`, startX, y);
            doc.text(splitText, startX + 5, y);
            y += splitText.length * 5 + 2;
        } else if (line.trim() === '') {
            checkPageBreak(lineHeight);
            y += lineHeight;
        } else {
            doc.setFontSize(11);
            renderStyledLine(line);
        }
    }
    return y;
};

export const generatePDF = (title: string, content: string, courseCode: string, year: number) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;

  // Header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("ADEKUNLE AJASIN UNIVERSITY, AKUNGBA-AKOKO", pageWidth / 2, 20, { align: "center" });
  
  doc.setFontSize(14);
  doc.text("FINANCE STUDENTS' ASSOCIATION", pageWidth / 2, 28, { align: "center" });

  doc.setLineWidth(0.5);
  doc.line(margin, 35, pageWidth - margin, 35);

  // Course Info
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Course Code: ${courseCode}`, margin, 45);
  doc.text(`Year: ${year}`, pageWidth - margin, 45, { align: "right" });
  
  doc.setFont("helvetica", "bold");
  doc.text(`Course Title: ${title}`, margin, 52);

  doc.line(margin, 58, pageWidth - margin, 58);

  // Content rendering using the new markdown-aware function
  renderMarkdownContent(doc, content, margin, 68, maxLineWidth);

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
      doc.text("Generated by FINSA Portal", margin, doc.internal.pageSize.getHeight() - 10);
      doc.setTextColor(0);
  }

  return doc;
};

export const downloadPDF = (title: string, content: string, courseCode: string, year: number) => {
    const doc = generatePDF(title, content, courseCode, year);
    doc.save(`${courseCode}_${year}_PastQuestion.pdf`);
};

export const generateTestReviewPDF = (questions: any[], userAnswers: Record<number, number>, score: number, user: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let yPos = 20;

    const checkPageBreak = (spaceNeeded: number) => {
        if (yPos + spaceNeeded > pageHeight - margin) {
            doc.addPage();
            yPos = 20;
        }
    };

    // Header
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("TEST RESULT SUMMARY", pageWidth / 2, yPos, { align: "center" });
    yPos += 10;
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Student: ${user?.name || 'Guest'}`, margin, yPos);
    yPos += 7;
    doc.text(`Score: ${score}%`, margin, yPos);
    yPos += 7;
    doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPos);
    yPos += 15;

    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    doc.setFontSize(11);
    
    questions.forEach((q, idx) => {
        const qTitle = `Q${idx + 1}: ${q.text}`;
        const splitTitle = doc.splitTextToSize(qTitle, maxLineWidth);
        const titleHeight = splitTitle.length * 6;

        checkPageBreak(titleHeight + 10);

        doc.setFont("helvetica", "bold");
        doc.text(splitTitle, margin, yPos);
        yPos += titleHeight + 4;

        doc.setFont("helvetica", "normal");
        q.options.forEach((opt: string, optIdx: number) => {
            const isCorrect = q.correctAnswer === optIdx;
            const isSelected = userAnswers[idx] === optIdx;
            
            let suffix = "";
            if (isCorrect) suffix += " (Correct)";
            if (isSelected && !isCorrect) suffix += " (Your Answer)";

            const optText = `${String.fromCharCode(65+optIdx)}. ${opt}${suffix}`;
            const splitOpt = doc.splitTextToSize(optText, maxLineWidth - 10);
            const optHeight = splitOpt.length * 6;

            checkPageBreak(optHeight + 2);

            if (isCorrect) doc.setTextColor(0, 150, 0); // Green
            else if (isSelected && !isCorrect) doc.setTextColor(200, 0, 0); // Red
            else doc.setTextColor(100, 100, 100);

            doc.text(splitOpt, margin + 5, yPos);
            doc.setTextColor(0, 0, 0);
            yPos += optHeight + 2;
        });
        
        yPos += 10;
    });

    const pageCount = (doc as any).internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: "center" });
    }

    doc.save(`FINQUEST_Test_Result_${new Date().toISOString().split('T')[0]}.pdf`);
};
