
import React, { useEffect, useState } from 'react';

interface FAQItem {
  category: string;
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  { category: 'General', question: "What is FINSA?", answer: "FINSA (Finance Students' Association) is the official digital portal for the Finance Department of Adekunle Ajasin University. It serves as a centralized hub for academic resources, news, and student interaction." },
  { category: 'General', question: "Who can use this portal?", answer: "The portal is strictly for students and staff of the Finance Department at AAUA. Guest users can view limited information." },
  { category: 'General', question: "Is the website mobile-friendly?", answer: "Yes, FINSA is fully responsive and optimized for all devices including Android and iOS phones." },
  { category: 'General', question: "How do I contact support?", answer: "You can use the contact details in the footer or the 'Contact Us' page to reach out via Email or WhatsApp." },
  
  { category: 'Academic', question: "How do I access past questions?", answer: "Navigate to the 'Archives' or 'Past Questions' page. You can filter questions by your level (100L-400L), year, or search by course code." },
  { category: 'Academic', question: "What is the CBT Practice feature?", answer: "The CBT Practice section allows you to take mock exams generated by our AI or standard question banks. It simulates real exam conditions to help you prepare." },
  { category: 'Academic', question: "How are test scores calculated?", answer: "Scores are calculated as a percentage. You earn points for passing: 2 points for 50-79%, and 5 points for 80%+." },
  { category: 'Academic', question: "Can I review my answers after a test?", answer: "Yes, after completing a test, you enter a 'Review Mode' where you can see correct answers and explanations." },
  { category: 'Academic', question: "Are the study materials free?", answer: "Yes, all materials provided on the portal are free for students." },
  
  { category: 'Account', question: "How do I verify my account?", answer: "Account verification (Blue Badge) is handled by the administrators. Ensure your profile details (Matric Number, Full Name) are accurate." },
  { category: 'Account', question: "I forgot my password.", answer: "On the login page, click 'Forgot Password?'. Enter your email to receive a reset link." },
  { category: 'Account', question: "How do I change my profile picture?", answer: "Go to your Profile page and click 'Edit Profile'. You can upload a new photo there." },
  { category: 'Account', question: "Why is my username taken?", answer: "Usernames must be unique across the platform. If your preferred name is taken, try adding numbers or variations." },
  
  { category: 'Community', question: "How can I join the WhatsApp group?", answer: "Go to the 'Community' page. There you will find direct links to join the official WhatsApp group, Telegram channel, and other social platforms." },
  { category: 'Community', question: "Can I delete my messages in the chat?", answer: "Yes, you can delete messages you have sent by clicking the trash icon next to them." },
  { category: 'Community', question: "Can I send images in the chat?", answer: "Yes, use the paperclip icon to attach images. You can also add a caption before sending." },
  
  { category: 'Contributions', question: "Can I upload materials?", answer: "Yes! We encourage contributions. Go to the 'Past Questions' page and click the upload button. Your submission will be reviewed by an admin before it appears on the site." },
  { category: 'Contributions', question: "Do I get points for uploading?", answer: "Yes, approved uploads award you 10 contribution points." },
  { category: 'Contributions', question: "What format should uploads be in?", answer: "We accept PDFs for documents and JPG/PNG for images. Please ensure scans are legible." }
];

const CATEGORIES = ['All', 'General', 'Academic', 'Account', 'Community', 'Contributions'];

export const FAQPage: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');

  useEffect(() => { window.scrollTo(0, 0); }, []);

  const filteredFaqs = faqs.filter(f => {
      const matchesSearch = f.question.toLowerCase().includes(searchTerm.toLowerCase()) || f.answer.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory = selectedCategory === 'All' || f.category === selectedCategory;
      return matchesSearch && matchesCategory;
  });

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 py-12 transition-colors">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="text-center mb-12">
          <span className="text-indigo-600 dark:text-indigo-400 font-bold tracking-widest text-xs uppercase mb-2 block">Support Center</span>
          <h1 className="text-4xl md:text-5xl font-serif font-bold text-slate-900 dark:text-white mb-4">Frequently Asked Questions</h1>
          <p className="text-slate-600 dark:text-slate-400 text-lg max-w-2xl mx-auto">Everything you need to know about the FINSA portal and department resources.</p>
        </div>

        <div className="bg-white dark:bg-slate-800 p-2 rounded-2xl shadow-sm mb-8 border border-slate-200 dark:border-slate-700 flex items-center">
            <svg className="w-6 h-6 text-slate-400 ml-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
            <input 
                type="text" 
                placeholder="Search questions..." 
                className="w-full p-3 bg-transparent text-slate-900 dark:text-white outline-none placeholder:text-slate-400"
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
            />
        </div>

        <div className="flex gap-2 overflow-x-auto pb-6 mb-2 scrollbar-hide">
            {CATEGORIES.map(cat => (
                <button 
                    key={cat}
                    onClick={() => setSelectedCategory(cat)}
                    className={`px-5 py-2.5 rounded-full text-sm font-bold whitespace-nowrap transition-all ${selectedCategory === cat ? 'bg-indigo-600 text-white shadow-md' : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700'}`}
                >
                    {cat}
                </button>
            ))}
        </div>

        <div className="space-y-4">
          {filteredFaqs.length > 0 ? filteredFaqs.map((faq, index) => (
            <div key={index} className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden transition-all duration-300 hover:shadow-md">
              <button 
                onClick={() => setActiveIndex(activeIndex === index ? null : index)} 
                className="w-full px-6 py-5 text-left flex justify-between items-center group focus:outline-none"
              >
                <span className={`font-bold text-lg transition-colors ${activeIndex === index ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-800 dark:text-slate-200'}`}>
                    {faq.question}
                </span>
                <span className={`transform transition-transform duration-300 bg-slate-100 dark:bg-slate-700 rounded-full p-1 text-slate-500 group-hover:bg-indigo-100 dark:group-hover:bg-indigo-900/30 group-hover:text-indigo-600 ${activeIndex === index ? 'rotate-180 bg-indigo-100 text-indigo-600' : ''}`}>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                </span>
              </button>
              <div className={`transition-all duration-300 ease-in-out overflow-hidden ${activeIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
                  <div className="px-6 pb-6 pt-0 text-slate-600 dark:text-slate-400 leading-relaxed border-t border-slate-100 dark:border-slate-700/50 mt-2 pt-4">
                    {faq.answer}
                  </div>
              </div>
            </div>
          )) : (
              <div className="text-center py-16">
                  <div className="text-6xl mb-4">🤔</div>
                  <p className="text-slate-500 dark:text-slate-400 font-medium">No questions found matching your search.</p>
              </div>
          )}
        </div>

        <div className="mt-16 text-center bg-indigo-50 dark:bg-slate-800/50 rounded-3xl p-8 border border-indigo-100 dark:border-slate-700">
          <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Still have questions?</h3>
          <p className="text-slate-600 dark:text-slate-400 mb-6">Can't find the answer you're looking for? Please chat to our friendly team.</p>
          <a href="mailto:finsa@gmail.com" className="inline-flex items-center gap-2 px-8 py-3 bg-indigo-600 text-white font-bold rounded-xl hover:bg-indigo-700 transition shadow-lg hover:-translate-y-1">
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
              Get in Touch
          </a>
        </div>
      </div>
    </div>
  );
};
