
import React, { useEffect, useState } from 'react';

interface FAQItem {
  category: string;
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  { category: 'General', question: "What is FINSA?", answer: "FINSA (Finance Students' Association) is the official digital portal for the Finance Department of Adekunle Ajasin University. It serves as a centralized hub for academic resources, news, and student interaction." },
  { category: 'General', question: "Who can use this portal?", answer: "The portal is strictly for students and staff of the Finance Department at AAUA. Guest users can view limited information." },
  { category: 'General', question: "Is the website mobile-friendly?", answer: "Yes, FINSA is fully responsive and optimized for all devices including Android and iOS phones." },
  { category: 'General', question: "Who developed this portal?", answer: "The portal was developed by the OBA - PRO '25/26 team to digitize departmental resources." },
  
  { category: 'Support', question: "How do I contact support?", answer: "For all inquiries, technical issues, or support, please contact the PRO solely via WhatsApp at 08142452729. Emails are no longer monitored for immediate support." },
  { category: 'Support', question: "Can I report a bug?", answer: "Yes, if you notice any glitches, please send a screenshot and description to the PRO via WhatsApp." },
  
  { category: 'Academic', question: "How do I access past questions?", answer: "Navigate to the 'Archives' or 'Past Questions' page. You can filter questions by your level (100L-400L), year, or search by course code." },
  { category: 'Academic', question: "What is the CBT Practice feature?", answer: "The CBT Practice section allows you to take mock exams generated by our AI or standard question banks. It simulates real exam conditions to help you prepare." },
  { category: 'Academic', question: "Why is the test page not loading questions?", answer: "If questions fail to load, check your internet connection as the AI requires a stable network to generate fresh questions. If the issue persists, try the 'Standard Mock' mode instead of Topic mode." },
  { category: 'Academic', question: "How are test scores calculated?", answer: "Scores are calculated as a percentage. You earn points for passing: 2 points for 50-79%, and 5 points for 80%+." },
  { category: 'Academic', question: "Can I review my answers after a test?", answer: "Yes, after completing a test, you enter a 'Review Mode' where you can see correct answers and explanations." },
  { category: 'Academic', question: "Are the study materials free?", answer: "Yes, all materials provided on the portal are free for students." },
  { category: 'Academic', question: "Can I download the materials?", answer: "Yes, most past questions and lecture notes are available for download in PDF format or as images." },
  { category: 'Academic', question: "Are lecture notes available?", answer: "Yes, you can find lecture notes under the Archives section. You can also generate AI summaries of topics using the 'Generate Notes' feature in the Admin panel (request via your course rep)." },
  
  { category: 'Account', question: "How do I verify my account?", answer: "Account verification (Blue Badge) is handled by the administrators. Ensure your profile details (Matric Number, Full Name) are accurate." },
  { category: 'Account', question: "I forgot my password.", answer: "On the login page, click 'Forgot Password?'. Enter your email to receive a reset link." },
  { category: 'Account', question: "How do I change my profile picture?", answer: "Go to your Profile page and click 'Edit Profile'. You can upload a new photo there." },
  { category: 'Account', question: "Why is my username taken?", answer: "Usernames must be unique across the platform. If your preferred name is taken, try adding numbers or variations." },
  { category: 'Account', question: "Can I change my level?", answer: "Yes, you can update your level in the Profile Edit section." },
  
  { category: 'Community', question: "How can I join the WhatsApp group?", answer: "Go to the 'Community' page. There you will find direct links to join the official WhatsApp group, Telegram channel, and other social platforms." },
  { category: 'Community', question: "Can I delete my messages in the chat?", answer: "Yes, you can delete messages you have sent by clicking the trash icon next to them." },
  { category: 'Community', question: "What are private notes?", answer: "The Notes feature allows you to save personal study jottings that only you can see. They are securely stored in your account." },
  
  { category: 'Contributions', question: "Can I upload materials?", answer: "Yes! We encourage contributions. Go to the 'Past Questions' page and click the upload button. Your submission will be reviewed by an admin before it appears on the site." },
  { category: 'Contributions', question: "Do I get points for uploading?", answer: "Yes, approved uploads award you 10 contribution points." },
  { category: 'Contributions', question: "What is the Leaderboard?", answer: "The leaderboard ranks students based on 'Contribution Points'. Points are earned by taking tests and uploading materials. It is a measure of your academic activity on the portal." }
];

const CATEGORIES = ['All', 'General', 'Academic', 'Support', 'Account', 'Community', 'Contributions'];

export const FAQPage: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');

  useEffect(() => { window.scrollTo(0, 0); }, []);

  const filteredFaqs = faqs.filter(f => {
      const matchesSearch = f.question.toLowerCase().includes(searchTerm.toLowerCase()) || f.answer.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory = selectedCategory === 'All' || f.category === selectedCategory;
      return matchesSearch && matchesCategory;
  });

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 py-12 transition-colors">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="text-center mb-12">
          <span className="text-indigo-600 dark:text-indigo-400 font-bold tracking-widest text-xs uppercase mb-2 block">Support Center</span>
          <h1 className="text-4xl md:text-5xl font-serif font-bold text-slate-900 dark:text-white mb-4">Frequently Asked Questions</h1>
          <p className="text-slate-600 dark:text-slate-400 text-lg max-w-2xl mx-auto">Everything you need to know about the FINSA portal and department resources.</p>
        </div>

        <div className="bg-white dark:bg-slate-800 p-2 rounded-2xl shadow-sm mb-8 border border-slate-200 dark:border-slate-700 flex items-center">
            <svg className="w-6 h-6 text-slate-400 ml-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
            <input 
                type="text" 
                placeholder="Search questions..." 
                className="w-full p-3 bg-transparent text-slate-900 dark:text-white outline-none placeholder:text-slate-400"
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
            />
        </div>

        <div className="flex gap-2 overflow-x-auto pb-6 mb-2 scrollbar-hide">
            {CATEGORIES.map(cat => (
                <button 
                    key={cat}
                    onClick={() => setSelectedCategory(cat)}
                    className={`px-5 py-2.5 rounded-full text-sm font-bold whitespace-nowrap transition-all ${selectedCategory === cat ? 'bg-indigo-600 text-white shadow-md' : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700'}`}
                >
                    {cat}
                </button>
            ))}
        </div>

        <div className="space-y-4">
          {filteredFaqs.length > 0 ? filteredFaqs.map((faq, index) => (
            <div key={index} className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden transition-all duration-300 hover:shadow-md">
              <button 
                onClick={() => setActiveIndex(activeIndex === index ? null : index)} 
                className="w-full px-6 py-5 text-left flex justify-between items-center group focus:outline-none"
              >
                <span className={`font-bold text-lg transition-colors ${activeIndex === index ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-800 dark:text-slate-200'}`}>
                    {faq.question}
                </span>
                <span className={`transform transition-transform duration-300 bg-slate-100 dark:bg-slate-700 rounded-full p-1 text-slate-500 group-hover:bg-indigo-100 dark:group-hover:bg-indigo-900/30 group-hover:text-indigo-600 ${activeIndex === index ? 'rotate-180 bg-indigo-100 text-indigo-600' : ''}`}>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                </span>
              </button>
              <div className={`transition-all duration-300 ease-in-out overflow-hidden ${activeIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
                  <div className="px-6 pb-6 pt-0 text-slate-600 dark:text-slate-400 leading-relaxed border-t border-slate-100 dark:border-slate-700/50 mt-2 pt-4">
                    {faq.answer}
                  </div>
              </div>
            </div>
          )) : (
              <div className="text-center py-16">
                  <div className="text-6xl mb-4">🤔</div>
                  <p className="text-slate-500 dark:text-slate-400 font-medium">No questions found matching your search.</p>
              </div>
          )}
        </div>

        <div className="mt-16 text-center bg-indigo-50 dark:bg-slate-800/50 rounded-3xl p-8 border border-indigo-100 dark:border-slate-700">
          <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Need direct help?</h3>
          <p className="text-slate-600 dark:text-slate-400 mb-6">Chat directly with the PRO on WhatsApp for instant support.</p>
          <a href="https://wa.me/2348142452729" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 px-8 py-3 bg-green-600 text-white font-bold rounded-xl hover:bg-green-700 transition shadow-lg hover:-translate-y-1">
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.017-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z"/></svg>
              Message PRO (08142452729)
          </a>
        </div>
      </div>
    </div>
  );
};
